export const COMPANY_LOGO_MAPPINGS: Record<string, string> = {
  Stripe: "logos:stripe",
  Airbnb: "logos:airbnb-icon",
  Qonto: "logos:qonto-icon",
  Figma: "logos:figma",
  Discord: "logos:discord-icon",
  Notion: "logos:notion-icon",
  Adobe: "logos:adobe-icon",
  Atlassian: "logos:atlassian",
  Uber: "simple-icons:uber",
  Twitch: "logos:twitch",
  Snowflake: "logos:snowflake-icon",
  OpenAI: "logos:openai-icon",
  Databricks: "simple-icons:databricks",
  Plaid: "logos:plaid",
  Roblox: "simple-icons:roblox",
  Coinbase: "logos:coinbase",
  DoorDash: "simple-icons:doordash",
  Palantir: "simple-icons:palantir",
  "Scale AI": "logos:scale-ai",
  Anthropic: "logos:anthropic",
  Retool: "logos:retool-icon",
  Rippling: "logos:rippling",
  Robinhood: "simple-icons:robinhood",
}; 